name: release
on:
  push:
    branches:
      - "dev"
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install PlatformIO
        run: python3 -m pip install platformio cryptography
      - name: Build firmwares
        run: FIRMWARE_VERSION=${{github.ref_name}} platformio run
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/firmware/*
          retention-days: 1
  release:
    name: Release
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for CHANGELOG
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware
      - name: Display structure of downloaded files
        run: ls -R
      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: true
            title: "Development Build"
            files: "firmware/*"
